### ISSUE TITLE
.NET Exception

### ISSUE THREAD

**Issue by deefrawley** [Xenolphthalein/Flow.Launcher.Plugin.ClipboardHistory#3]
Hi,

I receive the following exception 2 out of every 3 PC reboots since installing the plugin. The .NET error window pops up without me activating Flow at all

************** Exception Text **************
System.Runtime.InteropServices.ExternalException (0x800401D0): Requested Clipboard operation did not succeed.
   at System.Windows.Forms.Clipboard.GetDataObject(Int32 retryTimes, Int32 retryDelay)
   at System.Windows.Forms.Clipboard.GetDataObject()
   at Flow.Launcher.Plugin.ClipboardHistory.ClipboardMonitor.ClipboardWatcher.ClipChanged()
   at Flow.Launcher.Plugin.ClipboardHistory.ClipboardMonitor.ClipboardWatcher.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by deefrawley** [comment]
Just an update - it is happening every reboot/restart and it completely crashes Flow - I have to restart it after I OK the .NET exception window.

**Comment by deefrawley** [comment]
Flow 1.8.3 and fresh plugin install - now working??!! However this has been reported again at [693](https://github.com/Flow-Launcher/Flow.Launcher/issues/693). I tried copying text and a URL and both show in Flow. I even copied an image to the clipboard and the plugin still worked and only showed the text and URL clips. Restarted Flow several times and no exception. 
Will report back if this changes.

**Comment by deefrawley** [comment]
Scratch that - PC reboot and exception. Must be the state of the clipboard on system start that the plugin doesn't like
